# Generated by Django 6.0.1 on 2026-04-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0004_purity_parentlot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalreceipt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parentlot',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
