# Generated by Django 6.0.1 on 2026-04-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0005_alter_metalreceipt_date_alter_parentlot_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeltingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('in_weight', models.FloatField()),
                ('in_purity', models.FloatField()),
                ('required_weight', models.FloatField()),
                ('require_alloy_weight', models.FloatField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_lots', models.ManyToManyField(blank=True, related_name='melting_lots', to='mgmtapp.parentlot')),
                ('products', models.ManyToManyField(related_name='melting_lots', to='mgmtapp.product')),
                ('purity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melting_lots', to='mgmtapp.purity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melting_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
