# Generated by Django 6.0.1 on 2026-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0006_meltinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltinglot',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
