# Generated by Django 6.0.1 on 2026-04-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0007_meltinglot_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meltinglot',
            name='in_purity',
        ),
        migrations.RemoveField(
            model_name='meltinglot',
            name='in_weight',
        ),
        migrations.AddField(
            model_name='meltinglot',
            name='hook_purity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meltinglot',
            name='metal_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='melting_lots', to='mgmtapp.metalreceipt'),
        ),
    ]
