# Generated by Django 6.0.1 on 2026-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0008_remove_meltinglot_in_purity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meltinglot',
            name='hook_purity',
            field=models.FloatField(default=0),
        ),
    ]
