# Generated by Django 6.0.1 on 2026-05-01 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0011_departmentformrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentformconfig',
            unique_together={('user', 'department_name')},
        ),
        migrations.AddField(
            model_name='department',
            name='department_form_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='mgmtapp.departmentformconfig'),
        ),
        migrations.AlterField(
            model_name='departmentformconfig',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_form_configs', to='mgmtapp.department'),
        ),
    ]
