# Generated by Django 6.0.1 on 2026-05-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0013_remove_department_form_config_from_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='previous_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
    ]
