# Generated by Django 6.0.1 on 2026-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0014_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentformconfig',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='forms',
            field=models.ManyToManyField(blank=True, related_name='departments', to='mgmtapp.departmentformconfig'),
        ),
    ]
