# Generated by Django 6.0.1 on 2026-05-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0015_remove_departmentformconfig_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentformrecord',
            name='form_config',
        ),
        migrations.RemoveField(
            model_name='department',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='departmentformrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='departmentformrecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentformrecord',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='departmentformrecord',
            name='user',
        ),
        migrations.CreateModel(
            name='DepartmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=100)),
                ('lot_purity', models.FloatField()),
                ('in_weight', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('field_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_records_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='mgmtapp.department')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_records_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field_name', '-created_at'],
                'unique_together': {('user', 'field_name')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='departments', to='mgmtapp.fielddefinition'),
        ),
        migrations.DeleteModel(
            name='DepartmentFormConfig',
        ),
        migrations.DeleteModel(
            name='DepartmentFormRecord',
        ),
    ]
