# Generated by Django 6.0.1 on 2026-05-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0016_remove_departmentformrecord_form_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='departmentrecord',
            name='in_weight',
        ),
        migrations.RemoveField(
            model_name='departmentrecord',
            name='lot_no',
        ),
        migrations.RemoveField(
            model_name='departmentrecord',
            name='lot_purity',
        ),
        migrations.AddField(
            model_name='departmentrecord',
            name='melting_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_records', to='mgmtapp.meltinglot'),
        ),
    ]
