# Generated by Django 6.0.1 on 2026-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0017_remove_departmentrecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
