# Generated by Django 6.0.1 on 2026-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0018_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meltinglot',
            name='required_gold_weight',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
