# Generated by Django 6.0.1 on 2026-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0019_meltinglot_required_gold_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentrecord',
            name='out_weight',
            field=models.FloatField(default=0),
        ),
    ]
