# Generated by Django 6.0.1 on 2026-05-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0020_departmentrecord_out_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meltinglot',
            name='required_gold_weight',
        ),
    ]
