# Generated by Django 6.0.1 on 2026-05-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_replicas_and_link_melting_lots(apps, schema_editor):
    MetalReceipt = apps.get_model('mgmtapp', 'MetalReceipt')
    MetalReceiptReplica = apps.get_model('mgmtapp', 'MetalReceiptReplica')
    MeltingLot = apps.get_model('mgmtapp', 'MeltingLot')

    replica_by_receipt_id = {}
    for receipt in MetalReceipt.objects.all():
        replica, _ = MetalReceiptReplica.objects.update_or_create(
            source_receipt=receipt,
            defaults={
                'accounts': receipt.accounts,
                'type': receipt.type,
                'date': receipt.date,
                'description': receipt.description,
                'melting_purity': receipt.melting_purity,
                'in_weight': receipt.in_weight,
                'out_weight': receipt.out_weight,
                'balance_weight': receipt.balance_weight,
                'user_id': receipt.user_id,
                'is_active': receipt.is_active,
            },
        )
        replica_by_receipt_id[receipt.id] = replica.id

    for melting_lot in MeltingLot.objects.exclude(metal_receipt_id=None):
        replica_id = replica_by_receipt_id.get(melting_lot.metal_receipt_id)
        if replica_id:
            melting_lot.metal_receipt_replica_id = replica_id
            melting_lot.save(update_fields=['metal_receipt_replica'])


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0021_remove_meltinglot_required_gold_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalReceiptReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('melting_purity', models.FloatField()),
                ('in_weight', models.FloatField()),
                ('out_weight', models.FloatField(default=0)),
                ('balance_weight', models.FloatField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replica', to='mgmtapp.metalreceipt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metal_receipt_replicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meltinglot',
            name='metal_receipt_replica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='melting_lots', to='mgmtapp.metalreceiptreplica'),
        ),
        migrations.RunPython(create_replicas_and_link_melting_lots, migrations.RunPython.noop),
    ]
