# Generated by Django 6.0.1 on 2026-05-03 09:13

from django.db import migrations, models


def populate_receipt_numbers(apps, schema_editor):
    MetalReceipt = apps.get_model('mgmtapp', 'MetalReceipt')
    MetalReceiptReplica = apps.get_model('mgmtapp', 'MetalReceiptReplica')

    for receipt in MetalReceipt.objects.all():
        receipt_no = receipt.receipt_no or f"MR-{receipt.pk:06d}"
        if receipt.receipt_no != receipt_no:
            receipt.receipt_no = receipt_no
            receipt.save(update_fields=['receipt_no'])

        MetalReceiptReplica.objects.filter(source_receipt=receipt).update(receipt_no=receipt_no)


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtapp', '0022_metalreceiptreplica_meltinglot_metal_receipt_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalreceipt',
            name='receipt_no',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metalreceiptreplica',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(populate_receipt_numbers, migrations.RunPython.noop),
    ]
